import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import '../utils/app_logger.dart';

/// Detects an optional custom logo bundled at `assets/branding/app_icon_source.webp`.
///
/// **Not** `app_icon_source.png`, which this pointed at until the monochrome
/// redesign. That file is the 512px *launcher icon* — mark, dark rounded-square
/// background and all — generated by `tool/generate_launcher_icons.dart`, and it
/// is always present. Treating it as a logo override meant `hasCustomLogo` was
/// permanently true: the drawn mark never rendered anywhere, the 26px logo in
/// the onboarding bar was a shrunken app icon rather than a bare glyph, and
/// `AurixLogoBadge` drew a badge inside a badge on the splash, login, About and
/// setup screens.
///
/// The two files are different things and the surrounding docs always said so —
/// only the constant disagreed.
///
/// The probe runs once during `bootstrap()` and caches its answer, so
/// `AurixLogo` can decide synchronously on every build. The alternatives are
/// both worse: a `FutureBuilder` per logo would flash the fallback mark on
/// first frame, and `Image.asset`'s `errorBuilder` would log a bundle error
/// every time the app runs without a custom logo — which is the default.
abstract final class BrandAssets {
  static const String logoPath = 'assets/branding/app_icon_source.webp';

  static bool _hasCustomLogo = false;
  static bool _probed = false;

  /// True when a usable `logo.png` was found at startup.
  static bool get hasCustomLogo => _hasCustomLogo;

  /// Whether [detect] has run. Guards against reading the flag too early,
  /// which would silently render the fallback in a release build.
  static bool get isProbed => _probed;

  /// Looks for the custom logo. Safe to call more than once.
  static Future<void> detect() async {
    if (_probed) return;
    _probed = true;

    try {
      // Ask the manifest before asking the bundle. `rootBundle.load` on a
      // missing asset is handled fine on mobile, but on Flutter Web it is a
      // real HTTP request, and the engine logs the 404 to the browser console
      // before the exception ever reaches this catch:
      //
      //   Error while trying to load an asset: … logo.png … HTTP status 404
      //
      // That reads as a broken app on the default path, where the drawn mark
      // is the intended behaviour and nothing is wrong.
      final manifest = await AssetManifest.loadFromAssetBundle(rootBundle);
      if (!manifest.listAssets().contains(logoPath)) {
        _hasCustomLogo = false;
        return;
      }

      final data = await rootBundle.load(logoPath);
      // A declared-but-empty file is a common mistake (an interrupted copy, or
      // a Git LFS pointer that was never fetched). Treat it as absent rather
      // than letting the decoder fail later on a screen the user is looking at.
      _hasCustomLogo = data.lengthInBytes > 0;

      if (_hasCustomLogo) {
        AppLogger.info(
          'Using custom brand logo (${data.lengthInBytes ~/ 1024} KB)',
          scope: 'brand',
        );
      } else {
        AppLogger.warn(
          '$logoPath is empty; using the drawn mark',
          scope: 'brand',
        );
      }
    } on FlutterError {
      // Not bundled. The overwhelmingly common case, and not worth a warning.
      _hasCustomLogo = false;
    } on Object catch (error) {
      AppLogger.warn('Could not read $logoPath', scope: 'brand', error: error);
      _hasCustomLogo = false;
    }
  }

  /// Test hook: forces the flag without touching the asset bundle.
  static void debugSetHasCustomLogo(bool value) {
    _hasCustomLogo = value;
    _probed = true;
  }

  /// Test hook: returns the detector to its pre-probe state.
  static void debugReset() {
    _hasCustomLogo = false;
    _probed = false;
  }
}
